{
 "title": "Alerts-Actions",
 "description": "Prueba de Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatura CPU (°C)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pos_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024 ",
     "legendFormat": "RAM usada (GB)"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024 ",
     "legendFormat": "RAM disponible (GB)"
    },
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "% RAM usada"
    }
   ]
  },
  {
   "title": "Espacio Disponible (GB)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|efivarfs|squashfs\"} / 1024 / 1024 / 1024 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Red (Bytes/Segundo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[1m]) / 1024 / 1024 ",
     "legendFormat": "Trafico Recibido {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m]) / 1024 / 1024",
     "legendFormat": "Trafico Transmitido {{device}}"
    }
   ]
  },
  {
   "title": "Carga de Sistema (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by(cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) ",
     "legendFormat": "Núcleo {{cpu}}"
    }
   ]
  },
  {
   "title": "Uso total de CPU (%)",
   "type": "timeseries",
   "description": "Porcentaje de CPU en uso",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}