version: "3.8"

# Red personalizada para todos los servicios
networks:
  alloy_net:
    driver: bridge

# Volúmenes
volumes:
  grafana-storage:

# Servicios centrales
services:
  # Loki - Almacenamiento de logs
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - alloy_net
    restart: unless-stopped

  # Mimir - Almacenamiento de métricas
  mimir:
    image: grafana/mimir:2.11.0
    container_name: mimir
    ports:
      - "9009:9009"  # Para escritura de métricas
      - "9095:9095"  # Para consultas
    command:
      - -target=all
      - -config.file=/etc/mimir/config.yaml
    volumes:
      - ./mimir-config.yaml:/etc/mimir/config.yaml
    networks:
      - alloy_net
    restart: unless-stopped
    depends_on:
      - loki

  # Grafana - Visualización
  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - alloy_net
    restart: unless-stopped
    depends_on:
      - loki
      - mimir

  # Plantilla para nodos (no se inicia por defecto)
  node_template:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_TYPE: pos  # Valor por defecto, se sobrescribe al crear el contenedor
    container_name: alloy_node_template
    profiles: ["dont-start"]
    environment:
      - NODE_TYPE=pos  # Valor por defecto, se sobrescribe al crear el contenedor
    volumes:
      - ./data-alloy:/data-alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - ./hostlogs:/var/log/hostlogs
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    ports:
      - "9100:9100"    # Node Exporter
      - "9200:9200"    # Custom Exporter
      - "9300-9301:9300-9301"  # Retail POS Exporters
      - "9400-9401:9400-9401"  # Network Device Exporters
      - "12345:12345"  # Alloy UI
    networks:
      - alloy_net
    restart: unless-stopped
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
