version: "3.8"

services:
  alloy:
    build: .
    container_name: alloy-lab
    volumes:
      - ./hostlogs:/var/log/hostlogs
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    depends_on:
      - loki
      - mimir
    ports:
      - "12345:12345"
      - "9100:9100"
      - "9200:9200"
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  mimir:
    image: grafana/mimir:2.11.0
    container_name: mimir
    ports:
      - "9009:9009"
      - "9095:9095"
    command:
      - -target=all
      - -config.file=/etc/mimir/config.yaml
    volumes:
      - ./mimir-config.yaml:/etc/mimir/config.yaml

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - mimir