multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/data/tsdb

compactor:
  data_dir: /tmp/mimir/compactor

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

store_gateway:
  sharding_ring:
    kvstore:
      store: inmemory

server:
  http_listen_port: 9009
  grpc_listen_port: 9095
  log_level: info