apiVersion: 1
groups:
    - orgId: 1
      name: memory_group
      folder: Retail
      interval: 1m
      rules:
        - uid: dc6b6be6-9a53-4a86-97f0-11497d2f3c9f
          title: Memory Alert
          sendReminder: true
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PAE45454D0EDB9216
              model:
                editorMode: code
                expr: ((node_memory_MemTotal_bytes{nodename="Server-1"} - node_memory_MemAvailable_bytes{nodename="Server-1"}) / node_memory_MemTotal_bytes{nodename="Server-1"}) * 100
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 60
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 1m
          annotations:
            description: RAM - Alert
            summary: Memory has reached the maximum threshold
          labels:
            alert: iwrobot
          isPaused: false
