apiVersion: 1

datasources:
  # Mimir (Prometheus) datasource
  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    jsonData:
      httpMethod: POST
      timeInterval: "5s"
    version: 1

  # Loki datasource
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    version: 1