apiVersion: 1
contactPoints:
    - orgId: 1
      name: email receiver
      receivers:
        - uid: a429a46c-b490-46cb-904a-7e331bcf2b4e
          type: email
          settings:
            addresses: <example@email.com>
          disableResolveMessage: false
    - orgId: 1
      name: iwRobot
      receivers:
        - uid: ccc411ad-725c-4832-aab2-92d84dbddfa9
          type: webhook
          settings:
            httpMethod: POST
            password: admin
            url: http://fastapi_app:8000/webhook
          disableResolveMessage: false
